// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMpMTgcpNmwqr7WKz5ZOUgmsKz4Wv8jiI',
    appId: '1:366817422301:web:354316134a2ec7a7c5a434',
    messagingSenderId: '366817422301',
    projectId: 'jeevasethu-app',
    authDomain: 'jeevasethu-app.firebaseapp.com',
    storageBucket: 'jeevasethu-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNarDCfbQTPHw7F3QB-AOBC0mxBIfwVWw',
    appId: '1:366817422301:android:5554302c03bdb04cc5a434',
    messagingSenderId: '366817422301',
    projectId: 'jeevasethu-app',
    storageBucket: 'jeevasethu-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHodmRbV4td7QTWdu2DbhdGQMejw2Hedc',
    appId: '1:366817422301:ios:a34eaf2885e2642dc5a434',
    messagingSenderId: '366817422301',
    projectId: 'jeevasethu-app',
    storageBucket: 'jeevasethu-app.firebasestorage.app',
    iosBundleId: 'com.example.jeevasethu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHodmRbV4td7QTWdu2DbhdGQMejw2Hedc',
    appId: '1:366817422301:ios:a34eaf2885e2642dc5a434',
    messagingSenderId: '366817422301',
    projectId: 'jeevasethu-app',
    storageBucket: 'jeevasethu-app.firebasestorage.app',
    iosBundleId: 'com.example.jeevasethu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMpMTgcpNmwqr7WKz5ZOUgmsKz4Wv8jiI',
    appId: '1:366817422301:web:0c818b29fda31de1c5a434',
    messagingSenderId: '366817422301',
    projectId: 'jeevasethu-app',
    authDomain: 'jeevasethu-app.firebaseapp.com',
    storageBucket: 'jeevasethu-app.firebasestorage.app',
  );
}
